<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="N11 Test Suite" duration-ms="41814" started-at="2019-07-12T11:50:52Z" finished-at="2019-07-12T11:51:34Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="41814" started-at="2019-07-12T11:50:52Z" finished-at="2019-07-12T11:51:34Z">
      <class name="tests.ReactResendConfirmationEmailTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="setup" is-config="true" duration-ms="5255" started-at="2019-07-12T11:50:52Z" finished-at="2019-07-12T11:50:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TC_Negative_Verify_theError_messageDisplayed_whenUser_EnterInvalid_email()[pri:0, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="TC_Negative_Verify_theError_messageDisplayed_whenUser_EnterInvalid_email" duration-ms="14072" started-at="2019-07-12T11:50:57Z" description="Verify the error message displayed when user enter invalid Â email" finished-at="2019-07-12T11:51:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Negative_Verify_theError_messageDisplayed_whenUser_EnterInvalid_email -->
        <test-method status="PASS" signature="TC_Negative_Verify_theError_messageDisplayed_whenEmail_IsEmpty()[pri:1, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="TC_Negative_Verify_theError_messageDisplayed_whenEmail_IsEmpty" duration-ms="5409" started-at="2019-07-12T11:51:11Z" description="Verify the error message displayed by empty email field " finished-at="2019-07-12T11:51:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Negative_Verify_theError_messageDisplayed_whenEmail_IsEmpty -->
        <test-method status="FAIL" signature="TC_Negative_Verify_theError_messageDisplayed_whenUser_enterUnregistered_email()[pri:2, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="TC_Negative_Verify_theError_messageDisplayed_whenUser_enterUnregistered_email" duration-ms="5614" started-at="2019-07-12T11:51:17Z" description="Verify the error message displayed when user enter unregistered email" finished-at="2019-07-12T11:51:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Success: An email with password reset instructions has been sent to email@domain.com, if it exists on our system] but found [A server error happened. We are working to fix it.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Success: An email with password reset instructions has been sent to email@domain.com, if it exists on our system] but found [A server error happened. We are working to fix it.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.ReactResendConfirmationEmail.verifySuccessEmail(ReactResendConfirmationEmail.java:57)
at tests.ReactResendConfirmationEmailTest.TC_Negative_Verify_theError_messageDisplayed_whenUser_enterUnregistered_email(ReactResendConfirmationEmailTest.java:110)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Negative_Verify_theError_messageDisplayed_whenUser_enterUnregistered_email -->
        <test-method status="FAIL" signature="TC_Negative_Verify_theError_messageDisplayed_whenUser_enterregistered_emailand_ClickonButton()[pri:3, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="TC_Negative_Verify_theError_messageDisplayed_whenUser_enterregistered_emailand_ClickonButton" duration-ms="5635" started-at="2019-07-12T11:51:23Z" description="Verify the error message displayed when user enter registered email ID and then click on &#039;send reset instruction&#039; button" finished-at="2019-07-12T11:51:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Success: An email with password reset instructions has been sent to test@mailinator.com, if it exists on our system] but found [A server error happened. We are working to fix it.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Success: An email with password reset instructions has been sent to test@mailinator.com, if it exists on our system] but found [A server error happened. We are working to fix it.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.ReactResendConfirmationEmail.verifySuccessEmail(ReactResendConfirmationEmail.java:57)
at tests.ReactResendConfirmationEmailTest.TC_Negative_Verify_theError_messageDisplayed_whenUser_enterregistered_emailand_ClickonButton(ReactResendConfirmationEmailTest.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Negative_Verify_theError_messageDisplayed_whenUser_enterregistered_emailand_ClickonButton -->
        <test-method status="FAIL" signature="TC_Negative_Verify_theError_messageDisplayed_whenUser_shouldbe_ableToSend_PasswordLink()[pri:4, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="TC_Negative_Verify_theError_messageDisplayed_whenUser_shouldbe_ableToSend_PasswordLink" duration-ms="5458" started-at="2019-07-12T11:51:28Z" description="Verify the message and user should be able to able to send reset password link to registered emails" finished-at="2019-07-12T11:51:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Success: An email with password reset instructions has been sent to test@mailinator.com, if it exists on our system] but found [A server error happened. We are working to fix it.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Success: An email with password reset instructions has been sent to test@mailinator.com, if it exists on our system] but found [A server error happened. We are working to fix it.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.ReactResendConfirmationEmail.verifySuccessEmail(ReactResendConfirmationEmail.java:57)
at tests.ReactResendConfirmationEmailTest.TC_Negative_Verify_theError_messageDisplayed_whenUser_shouldbe_ableToSend_PasswordLink(ReactResendConfirmationEmailTest.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_Negative_Verify_theError_messageDisplayed_whenUser_shouldbe_ableToSend_PasswordLink -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.ReactResendConfirmationEmailTest@1e6d1014]" name="teardown" is-config="true" duration-ms="0" started-at="2019-07-12T11:51:34Z" finished-at="2019-07-12T11:51:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.ReactResendConfirmationEmailTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- N11 Test Suite -->
</testng-results>
